version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - chefmanager-network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      MONGO_URI: "mongodb://mongo:27017/chefmanager"
    networks:
      - chefmanager-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:5000"
    networks:
      - chefmanager-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - chefmanager-network
    depends_on:
      - frontend

volumes:
  mongo_data:

networks:
  chefmanager-network:
    external: true

